### ISSUE TITLE
Changes for new Zen update

### ISSUE THREAD

**Issue by devxan** [Alexcoder5/zen-sidebery#1]
Blending the background with Zen's own color: 
```css
#sidebar-box {
  background-color: transparent;
  color: var(--zen-colors-primary);
}
.sidebar-panel[lwt-sidebar] {
  background-color: transparent;
}
```

The border &/or shadow can be eliminated by removing the box-shadow and the border line:
```css
#zen-tabbox-wrapper {
  & #sidebar-box {
    border-radius: var(--zen-border-radius);
    box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
    margin-bottom: var(--zen-element-separation) !important;
    overflow: hidden;
    border: 1px solid var(--zen-colors-border);
  }
}
```

Thanks to @KiKaraage dev of [ArcWTF](https://github.com/KiKaraage/ArcWTF/) for this.
